### PR TITLE
Add CloudWatch Agent policy to instance role

### PR DESCRIPTION
**Pull request by jsf9k**
This AWS-provided policy will allow the instance to send logs and metrics to CloudWatch.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
I know it's just example code, but it still feels icky having real IPs checked in to the repo.  Can they be moved to a tfvars file?

**Comment by jsf9k** [comment]
> I know it's just example code, but it still feels icky having real IPs checked in to the repo. Can they be moved to a tfvars file?

@dav3r, see be9ae45.

**Review by mcdonnnj — APPROVED** [review]
Nice work. 👍

**Review by dav3r — APPROVED** [review]
👍 Thanks @jsf9k!

**Pull request merged**
